// Copies songs.json and live.json into public/ and writes the PWA manifest + service worker for the configured baseUrl.
import { readFileSync, writeFileSync, mkdirSync } from 'node:fs';

const app = JSON.parse(readFileSync('app.json', 'utf8')).expo;
const base = process.env.WEB_BASE_URL ?? app.experiments?.baseUrl ?? '';
mkdirSync('public', { recursive: true });

writeFileSync('public/songs.json', readFileSync('src/data/songs.json'));
writeFileSync('public/live.json', readFileSync('src/data/live.json'));

const manifest = {
  name: 'Chhath Countdown · छठ काउंटडाउन',
  short_name: 'Chhath',
  description: app.description,
  lang: 'hi',
  start_url: `${base}/`,
  scope: `${base}/`,
  display: 'standalone',
  orientation: 'portrait',
  background_color: '#FFF7EC',
  theme_color: '#D9480F',
  icons: [
    { src: `${base}/icons/icon-192.png`, sizes: '192x192', type: 'image/png' },
    { src: `${base}/icons/icon-512.png`, sizes: '512x512', type: 'image/png' },
    { src: `${base}/icons/maskable-512.png`, sizes: '512x512', type: 'image/png', purpose: 'maskable' },
  ],
};
writeFileSync('public/manifest.webmanifest', JSON.stringify(manifest, null, 2));

const version = new Date().toISOString();
const sw = `// Generated by scripts/prepare-web.mjs — ${version}
const CACHE = 'chhath-${version}';
const BASE = '${base}';
const SHELL = [BASE + '/', BASE + '/manifest.webmanifest', BASE + '/icons/icon-192.png'];

self.addEventListener('install', (e) => {
  e.waitUntil(caches.open(CACHE).then((c) => c.addAll(SHELL)).then(() => self.skipWaiting()));
});

self.addEventListener('activate', (e) => {
  e.waitUntil(
    caches.keys().then((keys) => Promise.all(keys.filter((k) => k !== CACHE).map((k) => caches.delete(k)))).then(() => self.clients.claim()),
  );
});

self.addEventListener('fetch', (e) => {
  const url = new URL(e.request.url);
  if (e.request.method !== 'GET' || url.origin !== self.location.origin) return;
  // Network first (fresh songs and pages), falling back to cache when offline.
  e.respondWith(
    fetch(e.request)
      .then((res) => {
        const copy = res.clone();
        caches.open(CACHE).then((c) => c.put(e.request, copy));
        return res;
      })
      .catch(() => caches.match(e.request).then((r) => r || caches.match(BASE + '/'))),
  );
});
`;
writeFileSync('public/sw.js', sw);
console.log(`Prepared web assets for base "${base}"`);
